name: Release Component A

on:
  workflow_dispatch:

# Restrict default permissions to read-only for security
permissions: read-all

env:
  COMP_NAME: comp-a
  SCA_SOURCES: "./dataprovider"

jobs:
  version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.version.outputs.version }}
      tag: ${{ steps.tagging.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Get current version
        id: version
        uses: codacy/git-version@2.8.6
      - name: Bump version and push tag
        id: tagging
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release:
    runs-on: ubuntu-latest
    needs: version
    permissions:
      packages: write
    steps:
      - id: repo-name-lowercase
        name: Convert repository owner to lowercase
        uses: iDevopsDemo/environment_cicd/.github/lowercase@main
        with:
          string: "${{ github.repository_owner }}"

      - uses: imjasonh/setup-crane@v0.1

      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ inputs.GITHUB_TOKEN }}

      - name: promote-image
        run: |
          REPO_NAME=ghcr.io/$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "Promoting image for ${REPO_NAME}/${{ env.COMP_NAME }} from version ${{ needs.version.outputs.version }} to tag ${{ needs.version.outputs.tag }}"
          crane auth login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
          crane cp ${REPO_NAME}/${{ env.COMP_NAME }}:${{ needs.version.outputs.version }} ${REPO_NAME}/${{ env.COMP_NAME }}:${{ needs.version.outputs.tag }}
          crane cp ${REPO_NAME}/${{ env.COMP_NAME }}:${{ needs.version.outputs.version }} ${REPO_NAME}/${{ env.COMP_NAME }}:latest
          crane cp ${REPO_NAME}/charts/${{ env.COMP_NAME }}:${{ needs.version.outputs.version }} ${REPO_NAME}/charts/${{ env.COMP_NAME }}:${{ needs.version.outputs.tag }}
        shell: bash
